config/routes.rb
Rails.application.routes.draw do

  root 'client#index'

  resources :client
  resources :server

end

app/models/upload.rb
class Upload < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/client_controller.rb
class ClientController < ApplicationController

  def index
    @files = Upload.all
  end

  def create
    @uploaded_io = params[:file]

    File.open(Rails.root.join('public', 'uploads', @uploaded_io.original_filename), 'wb') do |file|
      file.write(@uploaded_io.read)
    end

    @file = Upload.new({name: @uploaded_io.original_filename,
                        permission_download: true,
                        permission_rename: true,
                        permission_delete: true})
    @file.save
  end

  def destroy
    @file = Upload.find(params[:id])

    @path_to_file = "#{Rails.root}/public/uploads/#{@file.name}"
    File.delete(@path_to_file) if File.exist?(@path_to_file)

    @file.destroy

    redirect_to root_path
  end

  def show
    @file = Upload.find(params[:id])
    send_file "#{Rails.root}/public/uploads/#{@file.name}"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController



end

app/controllers/server_controller.rb
class ServerController < ApplicationController

  def index
    @files = Upload.all
  end

  def edit
    @file = Upload.find(params[:id])
  end

  def update
    @file = Upload.find(params[:id])

    if @file.update(file_params)
      redirect_to "/server"
    end
  end

  private
    def file_params
      params.require(:upload).permit(
          :permission_download, :permission_rename, :permission_delete)
    end

end

app/controllers/upload_controller.rb
class UploadController < ApplicationController

  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper

  def link_for_edit(record)
    link_to('Edit', edit_server_path(record))
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def link_for_download(record)
    if record.permission_download
      link_to('Download', client_path(record))
    end
  end

  def link_for_rename(record)
    if record.permission_rename
      link_to('Rename', client_path(record))
    end
  end

  def link_for_delete(record)
    if record.permission_delete
      link_to('Destroy', client_path(record),
              method: :delete,
              data: { confirm: "Are you sure you want to delete #{record.name} ?" })
    end
  end

end

app/helpers/server_helper.rb
module ServerHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/client/create.html.erb
File Saved!

app/views/client/index.html.erb
<%= form_tag({action: 'create'}, multipart: true) do %>
  <%= file_field_tag 'file' %>

  <br>
  <%= submit_tag 'Submit' %>
<% end %>

<% @files.each do |file| %>

  <%= file.name %>
  <%= link_for_download(file) %>
  <%= link_for_delete(file) %>
  <br>

<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Laba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/server/edit.html.erb
<%= form_for :upload, url: server_path(@file.id), method: :patch do |f| %>

  <%= @file.name %>
  <%= f.check_box :permission_download %>
  <%= f.check_box :permission_delete %>
  <%= f.submit "Update" %>

<% end %>

app/views/server/index.html.erb
<% @files.each do |file| %>

  <%= file.name %>
  <%= link_for_edit(file) %>
  <br>

<% end  %>

app/views/upload/index.html.erb
<%= form_tag('/upload', multipart: true) do %>
  <%= file_field_tag 'file' %>

  <br>
  <%= check_box_tag('permission_download', true, true) %>
  Download

  <br>
  <%= check_box_tag('permission_rename', true, true) %>
  Rename

  <br>
  <%= check_box_tag('permission_delete', true, true) %>
  Delete

  <br>
  <%= submit_tag 'Submit' %>
<% end %>